# syntax=docker/dockerfile:1
FROM golang:1.21-alpine AS builder
WORKDIR /build
COPY data-plane-proxy/go.mod data-plane-proxy/go.sum ./
RUN go mod download
COPY data-plane-proxy/ ./
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /zeta-gateway .

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /zeta-gateway /app/zeta-gateway
EXPOSE 8443
ENTRYPOINT ["/app/zeta-gateway"]
